"""fix gacha_execution status default and add check constraint

Revision ID: 4fc9c8f005f1
Revises: bedc36be83e2
Create Date: 2026-09-02 14:37:24.890439

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4fc9c8f005f1'
down_revision: str | Sequence[str] | None = 'bedc36be83e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_gacha_executions_status_valid', 'gacha_executions', "status IN ('ACQUIRED', 'COMPLETED', 'HASH_CONFLICT')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_gacha_executions_status_valid', 'gacha_executions', type_='check')
    # ### end Alembic commands ###
