"""create master tables

Revision ID: 939a1af225c4
Revises:
Create Date: 2026-09-01 11:23:47.612938

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "939a1af225c4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cats",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("persona", sa.String(), nullable=False),
        sa.Column("rarity", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "concepts",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "items",
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("price >= 0", name="ck_items_price_nonneg"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("template_code", sa.Text(), nullable=False),
        sa.Column("test_cases", sa.Text(), nullable=False),
        sa.Column("hint_text", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=False),
        sa.Column("house_level", sa.Integer(), nullable=False),
        sa.Column("wallpaper_item_id", sa.Integer(), nullable=True),
        sa.Column("floor_item_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("balance >= 0", name="ck_users_balance_nonneg"),
        sa.CheckConstraint("mileage >= 0", name="ck_users_mileage_nonneg"),
        sa.ForeignKeyConstraint(
            ["floor_item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallpaper_item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "attendances",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("check_in_date", sa.Date(), nullable=False),
        sa.Column("streak_count", sa.Integer(), nullable=False),
        sa.Column("daily_reward_claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("streak_count >= 1", name="ck_attendances_streak_positive"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("user_id", "check_in_date", name="uq_attendances_user_date"),
    )
    op.create_table(
        "gacha_executions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("operation_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("draw_count", sa.Integer(), nullable=True),
        sa.Column("balance_cost", sa.Integer(), nullable=False),
        sa.Column("result_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("balance_cost >= 0", name="ck_gacha_executions_cost_nonneg"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_table(
        "placed_objects",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("position_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "rooms",
        sa.Column("host_user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("max_participants > 0", name="ck_rooms_max_participants_positive"),
        sa.ForeignKeyConstraint(
            ["host_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "user_cats",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("cat_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "(cat_id IS NOT NULL) <> (item_id IS NOT NULL)", name="ck_user_cats_cat_xor_item"
        ),
        sa.CheckConstraint("cat_id IS NULL OR quantity = 1", name="ck_user_cats_cat_quantity_one"),
        sa.CheckConstraint("quantity > 0", name="ck_user_cats_quantity_positive"),
        sa.ForeignKeyConstraint(
            ["cat_id"],
            ["cats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("user_id", "cat_id", name="uq_user_cats_user_cat"),
        sa.UniqueConstraint("user_id", "item_id", name="uq_user_cats_user_item"),
    )
    op.create_table(
        "user_proficiency",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("proficiency_level", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("user_id", "concept_id", name="uq_user_proficiency_user_concept"),
    )
    op.create_table(
        "attendance_tasks",
        sa.Column("attendance_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("task_order", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("task_order > 0", name="ck_attendance_tasks_order_positive"),
        sa.ForeignKeyConstraint(
            ["attendance_id"],
            ["attendances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attendance_id", "task_id", name="uq_attendance_tasks_attendance_task"),
        sa.UniqueConstraint(
            "attendance_id", "task_order", name="uq_attendance_tasks_attendance_order"
        ),
        sa.UniqueConstraint("id", "task_id", name="uq_attendance_tasks_id_task_id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "cat_memories",
        sa.Column("user_cat_id", sa.Integer(), nullable=False),
        sa.Column("context_summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_cat_id"], ["user_cats.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "room_participants",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=True),
        sa.Column("current_score", sa.Integer(), nullable=False),
        sa.Column("is_ready", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("current_score >= 0", name="ck_room_participants_score_nonneg"),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("room_id", "user_id", name="uq_room_participants_room_user"),
    )
    op.create_table(
        "room_tasks",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("task_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("task_order > 0", name="ck_room_tasks_order_positive"),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "task_id", name="uq_room_tasks_id_task_id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("room_id", "task_id", name="uq_room_tasks_room_task"),
        sa.UniqueConstraint("room_id", "task_order", name="uq_room_tasks_room_order"),
    )
    op.create_table(
        "task_attempts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("attendance_task_id", sa.Integer(), nullable=True),
        sa.Column("room_task_id", sa.Integer(), nullable=True),
        sa.Column("context_type", sa.String(), nullable=False),
        sa.Column("submitted_code", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("used_hint", sa.Boolean(), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "(context_type = 'LEARNING' AND attendance_task_id IS NULL AND room_task_id IS NULL) OR (context_type = 'DAILY' AND attendance_task_id IS NOT NULL AND room_task_id IS NULL) OR (context_type = 'BATTLE' AND attendance_task_id IS NULL AND room_task_id IS NOT NULL)",
            name="ck_task_attempts_context_fk_match",
        ),
        sa.ForeignKeyConstraint(
            ["attendance_task_id", "task_id"],
            ["attendance_tasks.id", "attendance_tasks.task_id"],
            name="fk_task_attempts_attendance_task",
        ),
        sa.ForeignKeyConstraint(
            ["room_task_id", "task_id"],
            ["room_tasks.id", "room_tasks.task_id"],
            name="fk_task_attempts_room_task",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_attempts")
    op.drop_table("room_tasks")
    op.drop_table("room_participants")
    op.drop_table("cat_memories")
    op.drop_table("attendance_tasks")
    op.drop_table("user_proficiency")
    op.drop_table("user_cats")
    op.drop_table("rooms")
    op.drop_table("placed_objects")
    op.drop_table("gacha_executions")
    op.drop_table("attendances")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_table("tasks")
    op.drop_table("items")
    op.drop_table("concepts")
    op.drop_table("cats")
    # ### end Alembic commands ###
